- name: Install nginx on server
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
- name: Start and enabled nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
